### ISSUE TITLE
Merge header files in BB4D and BB6D

### ISSUE THREAD

**Issue by giadarol** [SixTrack/sixtracklib#25]
- At the moment the BB4D file does not contain any physics
 - Everything is defined in be_beambeam6d.h which should be renamed

**Comment by martinschwinzerl** [comment]
This has been addressed in #90. The common/be_beambeam folder has been renamed to common/be_beamfields and all implementations for 6D, 4D and the newly introduced space - charge elements have been bundled into 

be_beamfields/be_beamfields.h
be_beamfields/be_beamfields.c
be_beamfields/track.h

The missing pieces for full C++ and future API support have been relegated to #91, and #92
