### ISSUE TITLE
Settings.cmake.default: aperture typo

### ISSUE THREAD

**Issue by aoeftiger** [SixTrack/sixtracklib#65]
In the `Settings.cmake.default` top-level file, the aperture option for Y probably has a (copy-paste) typo:

lines 54-58:
```
set( SIXTRACKL_APERATURE_X_LIMIT_VALUE "1.0"
     CACHE STRING "Aperature check x limit" FORCE )

set( SIXTRACKL_APERATURE_Y_LIMIT_VALUE "1.0"
CACHE STRING "Aperature check x limit" FORCE )
```

--> should this be "Aperture check >y< limit"? (also I guess one would like to name it aperture instead of aperAture)

**Comment by martinschwinzerl** [comment]
This should, hopefully, embarrassingly and finally, been fixed in #73. Thank you for raising the issue!
